CREATE TABLE "TB_MEMBER" (
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(20)		NOT NULL,
	"NICKNAME"	VARCHAR2(100)		NULL,
	"PASSWORD"	VARCHAR2(300)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(300)		NOT NULL,
	"BIRTHDAY"	DATE		NULL,
	"PHONE"	CHAR(11)		NOT NULL,
	"MEMBER_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_GENDER"	CHAR(1)		NULL,
	"MEMBER_JOB"	VARCHAR2(50)		NULL,
	"MEMBER_ACHIEVE"	NUMBER		NULL,
	"ATTACH_NO"	NUMBER		NOT NULL
);

CREATE TABLE "CHAT_MESSAGE" (
	"CHAT_MESSAGE_NO"	NUMBER		NOT NULL,
	"CHAT_ROOM_NO"	VARCHAR2(100)		NOT NULL,
	"CHAR_USER_SENDER"	VARCHAR2(100)		NOT NULL,
	"CHAT_MESSAGE_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"CHAT_MESSAGE_At"	DATE		NULL,
	"CHAT_MESSAGE_TYPE_NO"	NUMBER		NOT NULL,
	"ATTACH_NO"	NUMBER		NOT NULL
);

--이 친구,,, 생성안됨
CREATE TABLE "GROUP" (
	"GROUP_NO"	varchar2(100)		NOT NULL,
	"CATEGORY_NO"	NUMBER		NULL,
	"GROUP_NAME"	VARCHAR2(100)		NOT NULL,
	"GROUP_ENROLL_DATE"	DATE		NOT NULL,
	"GROUP_CHARGE"	CHAR(1)		NULL,
	"GROUP_CLOSE"	CHAR(1)	DEFAULT 'N'	NULL,
	"GROUP_POOL"	NUMBER		NULL,
	"GROUP_PRIVATE"	CHAR(1)		NULL,
	"GROUP_LIKE_COUNT"	NUMBER	DEFAULT 0	NULL
);

CREATE TABLE "ATTACHMENT" (
	"ATTACH_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"GROUP_NO2"	varchar2(100)		NOT NULL,
	"ORIGINAL_FILENAME"	VARCHAR2(256)		NOT NULL,
	"RENAMED_FILENAME"	VARCHAR2(256)		NOT NULL,
	"REG_DATE"	DATE		NOT NULL,
	"IMG_FLAG"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"ATTACH_DELETED"	CHAR(1)	DEFAULT 'N'	NULL
);

CREATE TABLE "INTEREST_GROUP" (
	"INTER_NO"	VARCHAR2(200)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"GROUP_NO"	varchar2(100)		NOT NULL,
	"CATEGORY_NO"	NUMBER		NULL
);

CREATE TABLE "APPLOCATION_GROUP" (
	"ALG_NO"	VARCHAR2(200)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"GROUP_NO"	varchar2(100)		NOT NULL,
	"CATEGORY_NO"	NUMBER		NULL,
	"GROUP_ACCEPT"	CHAR(1)	DEFAULT 'N'	NULL,
	"ANSWER"	VARCHAR2(300)		NULL,
	"ROLE"	CHAR(1)	DEFAULT 'P'	NULL
);



CREATE TABLE "POST" (
	"POST_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"BOARD_NO"	VARCHAR2(100)		NOT NULL,
	"GROUP_NO"	VARCHAR2(100)		NOT NULL,
	"POST_TITLEV"	VARCHAR2(500)		NULL,
	"POST_CONTENT"	VARCHAR2(2000)		NULL,
	"POST_CATEGORY"	VARCHAR2(200)		NULL,
	"POST_REG_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"POST_UPDATE"	DATE		NULL,
	"ATTACH_NO"	NUMBER		NOT NULL
);

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"CONTENT"	VARCHAR2(2000)		NULL,
	"COMMENT_LEVEL"	NUMBER		NULL,
	"COMMENT_REF"	NUMBER		NULL,
	"REG_DATE"	DATE		NULL,
	"DELETE_YN"	CHAR(1)		NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

CREATE TABLE "BOOKMARK" (
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"GROUP_NO"	varchar2(100)		NOT NULL,
	"CATEGORY_NO"	NUMBER		NULL,
	"CHAT_NO"	NUMBER		NOT NULL,
	"NO2"	VARCHAR2(100)		NOT NULL,
	"NO3"	NUMBER		NOT NULL,
	"CHAT_ROOM_NO"	VARCHAR2(100)		NOT NULL,
	"CHAR_USER_SENDER"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "QUESTION" (
	"QUE_NO"	VARCHAR2(100)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'N'	NULL,
	"QUE_TITLE"	VARCHAR2(100)		NULL,
	"QUE_CONTENT"	VARCHAR2(2000)		NULL,
	"REG_DATE"	DATE		NULL,
	"ATTACH_NO"	NUMBER		NOT NULL
);



CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NULL,
	"NOTICE_TITLE"	VARCHAR2(500)		NULL,
	"NOTICE_CONTENT"	VARCHAR2(4000)		NULL
);

CREATE TABLE "TODOLISTDATE" (
	"TDLD_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"TDLD_SAVEDATE"	DATE		NULL
);

CREATE TABLE "DELETED_TB_MEMBER" (
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(20)		NOT NULL,
	"NICKNAME"	VARCHAR2(100)		NULL,
	"PASSWORD"	VARCHAR2(300)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(300)		NOT NULL,
	"BIRTHDAY"	DATE		NULL,
	"PHONE"	CHAR(11)		NOT NULL,
	"MEMBER_ENROLL_DATE"	DATE		NOT NULL,
	"MEMBER_QUIT"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_QUIT_DATE"	DATE		NULL,
	"MEMBER_GENDER"	CHAR(1)		NULL,
	"MEMBER_JOB"	VARCHAR2(50)		NULL,
	"MEMBER_ACHIEVE"	NUMBER		NULL,
	"ATTACH_NO"	NUMBER		NULL
);

CREATE TABLE "DELETED_GROUP" (
	"GROUP_NO"	varchar2(100)		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"GROUP_NAME"	VARCHAR2(100)		NOT NULL,
	"GROUP_ROLE"	CHAR(1)	DEFAULT 'U'	NOT NULL,
	"GROUP_ENORLL_DATE"	DATE		NOT NULL,
	"GROUP_CHARGE"	CHAR(1)	DEFAULT 'N'	NULL,
	"GROUP_POOL"	NUMBER		NOT NULL,
	"GROUP_PRIVATE"	CHAR(1)		NULL,
	"GROUP_LIKE_COUNT"	NUMBER		NULL
);

CREATE TABLE "GROUPINFO" (
	"GI_NO"	VARCHAR2(100)		NOT NULL,
	"SEQ_NO"	VARCHAR2(100)		NOT NULL,
	"GI_SUB_TITLE"	VARCHAR2(100)		NULL,
	"GI_CONTENT"	VARCHAR2(2000)		NULL
);

CREATE TABLE "ALARAM" (
	"ALARM_NO"	VARCHAR2(200)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"ALARM_FOR"	VARCHAR2(100)		NULL,
	"ALARM_REG_DATE"	DATE		NULL,
	"ALARM_UPDATE"	DATE		NULL,
	"ALARM_CONTENT"	VARCHAR2(500)		NULL
);

CREATE TABLE "MAP" (
	"MAP_NO"	VARCHAR2(100)		NOT NULL,
	"MAP_LATITUDE"	NUMBER		NULL,
	"MAP_LONGITUDE"	NUMBER		NULL,
	"MAP_ADDRESS"	VARCHAR2(120)		NULL
);

CREATE TABLE "Like" (
	"LIKE_NO"	VARCHAR2(200)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"GROUP_NO"	varchar2(100)		NOT NULL,
	"CATEGORY_NO"	VARCHAR2(200)		NULL
);

CREATE TABLE "SCHEDULE" (
	"SCHEDULE_NO"	VARCHAR2(100)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"TITLE"	VARCHAR2(100)		NULL,
	"CONTENT"	VARCHAR2(300)		NULL,
	"START_DATE"	DATE		NULL,
	"END_DATE"	DATE		NULL,
	"CATEGORY"	CHAR(1)	DEFAULT 'P'	NULL,
	"DELETED"	CHAR(1)	DEFAULT 'N'	NULL
);


CREATE TABLE "TODOLIST" (
	"TDL_NO"	VARCHAR2(100)		NOT NULL,
	"TDL_TITLE"	VARCHAR2(500)		NULL,
	"TDL_CONTENT"	VARCHAR2(1000)		NULL,
	"TDL_CHECKED"	CHAR(1)		NULL,
	"TDL_CREATE_TIME"	DATE		NULL,
	"TDL_UPDATE_TIME"	DATE		NULL,
	"TDL_START_TIME"	DATE		NULL,
	"TDL_END_TIME"	DATE		NULL
);

CREATE TABLE "TODOCOMMENT" (
	"TDLC_NO"	VARCHAR2(100)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"GROUP_NO"	varchar2(100)		NOT NULL,
	"CATEGORY_NO"	NUMBER		NULL,
	"TDLC_TITLE"	VARCHAR2(100)		NULL,
	"TDLC_CONTENT"	VARCHAR2(1000)		NULL,
	"TDLC_REG_DATE"	DATE		NULL
);

CREATE TABLE "STUDYGROUP_CATEGORY1" (
	"CATEGORY1_NO"	NUMBER		NULL,
	"CATEGOTY1_NAME"	VARCHAR2(200)		NULL
);

CREATE TABLE "STUDYGROUP_CATEGORY2" (
	"CATEGORY2_NO"	NUMBER		NULL,
	"CATEGOTY2_NAME"	VARCHAR2(200)		NULL
);

CREATE TABLE "BAN" (
	"BAN_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"GROUP_NO"	varchar2(100)		NOT NULL
);

CREATE TABLE "DELETED_BOARD" (
	"BOARD_NO"	VARCHAR2(100)		NOT NULL,
	"GROUP_NO"	VARCHAR2(100)		NULL,
	"BOARD_NAME"	VARCHAR2(200)		NULL
);

CREATE TABLE "DELETED_COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NULL,
	"CONTENT"	VARCHAR2(2000)		NULL,
	"COMMENT_LEVEL"	NUMBER		NULL,
	"COMMENT_REF"	NUMBER		NULL,
	"REG_DATE"	DATE		NULL,
	"DELETE_YN"	CHAR(1)		NULL,
	"BOARD_NO"	NUMBER		NULL
);

CREATE TABLE "GROUP_CATEGORY" (
	"NO"	NUMBER		NOT NULL,
	"GROUP_NO"	varchar2(100)		NOT NULL,
	"CATEGORY2_NO"	NUMBER		NULL
);

CREATE TABLE "CHAT_ROOM" (
	"CHAT_ROOM_NO"	VARCHAR2(100)		NOT NULL,
	"CHAR_USER_SENDER"	VARCHAR2(100)		NOT NULL,
	"CHAT_ROOM_NAME"	VARCHAR2(200)		NULL,
	"CHAT_ROOM_PUSH"	CHAR(1)		NULL,
	"CHAT_NEW"	CHAR(1)		NULL,
	"CHAT_REG_DATE"	DATE		NULL,
	"CHAT_UPDATE"	DATE		NULL
);

CREATE TABLE "CHAT_MESSAGE_TYPE" (
	"CHAT_MESSAGE_TYPE_NO"	NUMBER		NOT NULL,
	"TYPE"	VARCHAR2(50)	DEFAULT 'TEXT'	NULL
);


CREATE TABLE "CHAT_USER" (
	"CHAT_USER_NO"	VARCHAR2(100)		NOT NULL,
	"CHAR_USER_SENDER"	VARCHAR2(100)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"CHAT_ADMIN_ID"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "CHAT_ADMIN" (
	"CHAT_ADMIN_ID"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "DM" (
	"DM_NO"	NUMBER		NOT NULL,
	"DM_SENDER"	VARCHAR2(100)		NOT NULL,
	"DM_RECEIVER"	VARCHAR2(100)		NOT NULL,
	"DM_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"DM_MESSAGE_At"	DATE		NULL,
	"CHAT_MESSAGE_TYPE_NO"	NUMBER		NOT NULL,
	"ATTACH_NO"	NUMBER		NOT NULL
);

CREATE TABLE "BOARD" (
	"BOARD_NO"	VARCHAR2(100)		NOT NULL,
	"GROUP_NO"	VARCHAR2(100)		NOT NULL,
	"BOARD_NAME"	VARCHAR2(200)		NULL
);

--이친구도 문제있음 group_groupinfo는 생성 됨
CREATE TABLE "GROUP-GROUPINFO" (
	"SEQ_NO"	VARCHAR2(100)		NOT NULL,
	"GROUP_NO"	varchar2(100)		NOT NULL,
	"GI_TITLE"	VARCHAR2(100)		NULL,
	"ATTACH_NO"	NUMBER		NOT NULL
);

CREATE TABLE "GROUPINFO-COMMENT" (
	"SEQ_NO"	VARCHAR2(100)		NOT NULL,
	"SEQ_NO2"	VARCHAR2(100)		NOT NULL,
	"GROUP_NO"	varchar2(100)		NOT NULL,
	"GI_COMMENT"	VARCHAR2(100)		NULL
);

CREATE TABLE "authorities" (
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"authority"	VARCHAR2(20)	DEFAULT 'U'	NULL
);


CREATE TABLE "DELETED_QUESTION" (
	"QUE_NO"	VARCHAR2(100)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"STATUS"	VARCHAR(255)		NULL,
	"QUE_TITLE"	VARCHAR2(100)		NULL,
	"QUE_CONTENT"	VARCHAR2(2000)		NULL,
	"REG_DATE"	DATE		NULL,
	"ATTACH_NO"	NUMBER		NULL
);

CREATE TABLE "DELETED_POST" (
	"POST_NO"	NUMBER		NULL,
	"MEMBER_ID"	VARCHAR2(100)		NULL,
	"BOARD_NO"	VARCHAR2(100)		NULL,
	"GROUP_NO"	VARCHAR2(100)		NULL,
	"POST_TITLEV"	VARCHAR2(500)		NULL,
	"POST_CONTENT"	VARCHAR2(2000)		NULL,
	"POST_CATEGORY"	VARCHAR2(200)		NULL,
	"POST_REG_DATE"	DATE		NULL,
	"POST_UPDATE"	DATE		NULL,
	"ATTACH_NO"	NUMBER		NULL
);

ALTER TABLE "TB_MEMBER" ADD CONSTRAINT "PK_TB_MEMBER" PRIMARY KEY (
	"MEMBER_ID"
);

ALTER TABLE "CHAT_MESSAGE" ADD CONSTRAINT "PK_CHAT_MESSAGE" PRIMARY KEY (
	"CHAT_MESSAGE_NO",
	"CHAT_ROOM_NO",
	"CHAR_USER_SENDER"
);

ALTER TABLE "GROUP" ADD CONSTRAINT "PK_GROUP" PRIMARY KEY (
	"GROUP_NO",
	"CATEGORY_NO"
);

ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "PK_ATTACHMENT" PRIMARY KEY (
	"ATTACH_NO",
	"MEMBER_ID",
	"GROUP_NO2"
);

ALTER TABLE "INTEREST_GROUP" ADD CONSTRAINT "PK_INTEREST_GROUP" PRIMARY KEY (
	"INTER_NO",
	"MEMBER_ID",
	"GROUP_NO",
	"CATEGORY_NO"
);

ALTER TABLE "APPLOCATION_GROUP" ADD CONSTRAINT "PK_APPLOCATION_GROUP" PRIMARY KEY (
	"ALG_NO",
	"MEMBER_ID",
	"GROUP_NO",
	"CATEGORY_NO"
);

ALTER TABLE "POST" ADD CONSTRAINT "PK_POST" PRIMARY KEY (
	"POST_NO",
	"MEMBER_ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO",
	"MEMBER_ID"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "PK_BOOKMARK" PRIMARY KEY (
	"MEMBER_ID",
	"GROUP_NO",
	"CATEGORY_NO"
);

ALTER TABLE "QUESTION" ADD CONSTRAINT "PK_QUESTION" PRIMARY KEY (
	"QUE_NO",
	"MEMBER_ID"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "TODOLISTDATE" ADD CONSTRAINT "PK_TODOLISTDATE" PRIMARY KEY (
	"TDLD_NO",
	"MEMBER_ID"
);

ALTER TABLE "DELETED_TB_MEMBER" ADD CONSTRAINT "PK_DELETED_TB_MEMBER" PRIMARY KEY (
	"MEMBER_ID"
);

ALTER TABLE "DELETED_GROUP" ADD CONSTRAINT "PK_DELETED_GROUP" PRIMARY KEY (
	"GROUP_NO"
);

ALTER TABLE "GROUPINFO" ADD CONSTRAINT "PK_GROUPINFO" PRIMARY KEY (
	"GI_NO",
	"SEQ_NO"
);

ALTER TABLE "ALARAM" ADD CONSTRAINT "PK_ALARAM" PRIMARY KEY (
	"ALARM_NO",
	"MEMBER_ID"
);

ALTER TABLE "MAP" ADD CONSTRAINT "PK_MAP" PRIMARY KEY (
	"MAP_NO"
);

ALTER TABLE "Like" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY (
	"LIKE_NO",
	"MEMBER_ID",
	"GROUP_NO",
	"CATEGORY_NO"
);

ALTER TABLE "SCHEDULE" ADD CONSTRAINT "PK_SCHEDULE" PRIMARY KEY (
	"SCHEDULE_NO",
	"MEMBER_ID"
);

ALTER TABLE "TODOLIST" ADD CONSTRAINT "PK_TODOLIST" PRIMARY KEY (
	"TDL_NO"
);

ALTER TABLE "TODOCOMMENT" ADD CONSTRAINT "PK_TODOCOMMENT" PRIMARY KEY (
	"TDLC_NO",
	"MEMBER_ID",
	"GROUP_NO",
	"CATEGORY_NO"
);

ALTER TABLE "STUDYGROUP_CATEGORY1" ADD CONSTRAINT "PK_STUDYGROUP_CATEGORY1" PRIMARY KEY (
	"CATEGORY1_NO"
);

ALTER TABLE "STUDYGROUP_CATEGORY2" ADD CONSTRAINT "PK_STUDYGROUP_CATEGORY2" PRIMARY KEY (
	"CATEGORY2_NO"
);

ALTER TABLE "BAN" ADD CONSTRAINT "PK_BAN" PRIMARY KEY (
	"BAN_NO",
	"MEMBER_ID",
	"GROUP_NO"
);

ALTER TABLE "GROUP_CATEGORY" ADD CONSTRAINT "PK_GROUP_CATEGORY" PRIMARY KEY (
	"NO",
	"GROUP_NO",
	"CATEGORY2_NO"
);

ALTER TABLE "CHAT_ROOM" ADD CONSTRAINT "PK_CHAT_ROOM" PRIMARY KEY (
	"CHAT_ROOM_NO",
	"CHAR_USER_SENDER"
);

ALTER TABLE "CHAT_MESSAGE_TYPE" ADD CONSTRAINT "PK_CHAT_MESSAGE_TYPE" PRIMARY KEY (
	"CHAT_MESSAGE_TYPE_NO"
);

ALTER TABLE "CHAT_USER" ADD CONSTRAINT "PK_CHAT_USER" PRIMARY KEY (
	"CHAT_USER_NO",
	"CHAR_USER_SENDER"
);

ALTER TABLE "CHAT_ADMIN" ADD CONSTRAINT "PK_CHAT_ADMIN" PRIMARY KEY (
	"CHAT_ADMIN_ID"
);

ALTER TABLE "DM" ADD CONSTRAINT "PK_DM" PRIMARY KEY (
	"DM_NO",
	"DM_SENDER",
	"DM_RECEIVER"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO",
	"GROUP_NO"
);

ALTER TABLE "GROUP-GROUPINFO" ADD CONSTRAINT "PK_GROUP-GROUPINFO" PRIMARY KEY (
	"SEQ_NO",
	"GROUP_NO"
);

ALTER TABLE "GROUPINFO-COMMENT" ADD CONSTRAINT "PK_GROUPINFO-COMMENT" PRIMARY KEY (
	"SEQ_NO",
	"SEQ_NO2",
	"GROUP_NO"
);

ALTER TABLE "authorities" ADD CONSTRAINT "PK_AUTHORITIES" PRIMARY KEY (
	"MEMBER_ID"
);

ALTER TABLE "DELETED_QUESTION" ADD CONSTRAINT "PK_DELETED_QUESTION" PRIMARY KEY (
	"QUE_NO"
);

ALTER TABLE "CHAT_MESSAGE" ADD CONSTRAINT "FK_CHAT_ROOM_TO_CHAT_MESSAGE_1" FOREIGN KEY (
	"CHAT_ROOM_NO"
)
REFERENCES "CHAT_ROOM" (
	"CHAT_ROOM_NO"
);

ALTER TABLE "CHAT_MESSAGE" ADD CONSTRAINT "FK_CHAT_ROOM_TO_CHAT_MESSAGE_2" FOREIGN KEY (
	"CHAR_USER_SENDER"
)
REFERENCES "CHAT_ROOM" (
	"CHAR_USER_SENDER"
);

ALTER TABLE "GROUP" ADD CONSTRAINT "FK_STUDYGROUP_CATEGORY1_TO_GROUP_1" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "STUDYGROUP_CATEGORY1" (
	"CATEGORY1_NO"
);

ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "FK_TB_MEMBER_TO_ATTACHMENT_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "FK_GROUP_TO_ATTACHMENT_1" FOREIGN KEY (
	"GROUP_NO2"
)
REFERENCES "GROUP" (
	"GROUP_NO"
);

ALTER TABLE "INTEREST_GROUP" ADD CONSTRAINT "FK_TB_MEMBER_TO_INTEREST_GROUP_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "INTEREST_GROUP" ADD CONSTRAINT "FK_GROUP_TO_INTEREST_GROUP_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "GROUP" (
	"GROUP_NO"
);

ALTER TABLE "INTEREST_GROUP" ADD CONSTRAINT "FK_GROUP_TO_INTEREST_GROUP_2" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "GROUP" (
	"CATEGORY_NO"
);

ALTER TABLE "APPLOCATION_GROUP" ADD CONSTRAINT "FK_TB_MEMBER_TO_APPLOCATION_GROUP_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "APPLOCATION_GROUP" ADD CONSTRAINT "FK_GROUP_TO_APPLOCATION_GROUP_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "GROUP" (
	"GROUP_NO"
);

ALTER TABLE "APPLOCATION_GROUP" ADD CONSTRAINT "FK_GROUP_TO_APPLOCATION_GROUP_2" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "GROUP" (
	"CATEGORY_NO"
);

ALTER TABLE "POST" ADD CONSTRAINT "FK_TB_MEMBER_TO_POST_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_TB_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "FK_TB_MEMBER_TO_BOOKMARK_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "FK_GROUP_TO_BOOKMARK_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "GROUP" (
	"GROUP_NO"
);

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "FK_GROUP_TO_BOOKMARK_2" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "GROUP" (
	"CATEGORY_NO"
);

ALTER TABLE "QUESTION" ADD CONSTRAINT "FK_TB_MEMBER_TO_QUESTION_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "TODOLISTDATE" ADD CONSTRAINT "FK_TB_MEMBER_TO_TODOLISTDATE_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "GROUPINFO" ADD CONSTRAINT "FK_GROUP-GROUPINFO_TO_GROUPINFO_1" FOREIGN KEY (
	"SEQ_NO"
)
REFERENCES "GROUP-GROUPINFO" (
	"SEQ_NO"
);

ALTER TABLE "ALARAM" ADD CONSTRAINT "FK_TB_MEMBER_TO_ALARAM_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "Like" ADD CONSTRAINT "FK_TB_MEMBER_TO_Like_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "Like" ADD CONSTRAINT "FK_GROUP_TO_Like_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "GROUP" (
	"GROUP_NO"
);

ALTER TABLE "Like" ADD CONSTRAINT "FK_GROUP_TO_Like_2" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "GROUP" (
	"CATEGORY_NO"
);

ALTER TABLE "SCHEDULE" ADD CONSTRAINT "FK_TB_MEMBER_TO_SCHEDULE_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "TODOCOMMENT" ADD CONSTRAINT "FK_APPLOCATION_GROUP_TO_TODOCOMMENT_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "APPLOCATION_GROUP" (
	"MEMBER_ID"
);

ALTER TABLE "TODOCOMMENT" ADD CONSTRAINT "FK_APPLOCATION_GROUP_TO_TODOCOMMENT_2" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "APPLOCATION_GROUP" (
	"GROUP_NO"
);

ALTER TABLE "TODOCOMMENT" ADD CONSTRAINT "FK_APPLOCATION_GROUP_TO_TODOCOMMENT_3" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "APPLOCATION_GROUP" (
	"CATEGORY_NO"
);

ALTER TABLE "BAN" ADD CONSTRAINT "FK_TB_MEMBER_TO_BAN_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "BAN" ADD CONSTRAINT "FK_GROUP_TO_BAN_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "GROUP" (
	"GROUP_NO"
);

ALTER TABLE "GROUP_CATEGORY" ADD CONSTRAINT "FK_GROUP_TO_GROUP_CATEGORY_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "GROUP" (
	"GROUP_NO"
);

ALTER TABLE "GROUP_CATEGORY" ADD CONSTRAINT "FK_STUDYGROUP_CATEGORY2_TO_GROUP_CATEGORY_1" FOREIGN KEY (
	"CATEGORY2_NO"
)
REFERENCES "STUDYGROUP_CATEGORY2" (
	"CATEGORY2_NO"
);

ALTER TABLE "CHAT_ROOM" ADD CONSTRAINT "FK_CHAT_USER_TO_CHAT_ROOM_1" FOREIGN KEY (
	"CHAR_USER_SENDER"
)
REFERENCES "CHAT_USER" (
	"CHAR_USER_SENDER"
);

ALTER TABLE "DM" ADD CONSTRAINT "FK_TB_MEMBER_TO_DM_1" FOREIGN KEY (
	"DM_RECEIVER"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_GROUP_TO_BOARD_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "GROUP" (
	"GROUP_NO"
);

ALTER TABLE "GROUP-GROUPINFO" ADD CONSTRAINT "FK_GROUP_TO_GROUP-GROUPINFO_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "GROUP" (
	"GROUP_NO"
);

ALTER TABLE "GROUPINFO-COMMENT" ADD CONSTRAINT "FK_GROUP-GROUPINFO_TO_GROUPINFO-COMMENT_1" FOREIGN KEY (
	"SEQ_NO2"
)
REFERENCES "GROUP-GROUPINFO" (
	"SEQ_NO"
);

ALTER TABLE "GROUPINFO-COMMENT" ADD CONSTRAINT "FK_GROUP-GROUPINFO_TO_GROUPINFO-COMMENT_2" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "GROUP-GROUPINFO" (
	"GROUP_NO"
);

ALTER TABLE "authorities" ADD CONSTRAINT "FK_TB_MEMBER_TO_authorities_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "TB_MEMBER" (
	"MEMBER_ID"
);
